# Uncomment the next line to define a global platform for your project
use_frameworks!
 platform :ios, '9.0'

target 'vastExample' do
  pod 'SummerSlider'
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.5'

end
